version: '3.8'

services:
  mysqlOP:
    image: mysql:5.7
    container_name: organo-project-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: organo_project
    networks:
      - organo_project_rede

  front-end:
    image: carlosedusc/organo_project_front:1.0
    container_name: organo-project-front-end
    ports:
      - 5173:5173
    networks:
      - organo_project_rede
    depends_on:
      - back-end

  back-end:
    image: carlosedusc/organo_project_back:1.0
    container_name: organo-project-back-end
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlFD:3306/organo_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: 
     - organo_project_rede
    depends_on:
      - mysqlOP

networks:
  organo_project_rede:
    driver: bridge