version: '3.8'

services:
  mysqlFD:
    image: mysql:5.7
    container_name: formulario-dados-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario_dados
    networks:
      - formulario_dados_rede

  front-end:
    image: carlosedusc/formulario_dados_front:latest
    container_name: formulario-dados-front-end
    ports:
      - 5173:5173
    networks:
      - formulario_dados_rede
    depends_on:
      - back-end

  back-end:
    image: carlosedusc/formulario_dados_back
    container_name: formulario-dados-back-end
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlFD:3306/formulario_dados
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks: 
     - formulario_dados_rede
    depends_on:
      - mysqlFD

networks:
  formulario_dados_rede:
    driver: bridge